# NumPy

In [4]:
import numpy as np

## Basic Array Creation

In [5]:
# Numpy Array Same Data Type # --> ALSO CALLED VECTOR IF 1-D
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [ ]:
#--------------------------------------------------------------------------#
# Converts every data type to same data type if list has different data type #
#--------------------------------------------------------------------------#

a=[1,2,3,4,"hello"] # list
brr=np.array(a)
print(brr) # Converts to String

a1=[1,2,3,4,3.5] # list
brr1=np.array(a1)
print(brr1) # Converts to Float

['1' '2' '3' '4' 'hello']
[1.  2.  3.  4.  3.5]


In [10]:
# ------------------------ #
# Dont Support 2-D in List #
# ------------------------ #

l=[[1,2,3],[4,5,6],[7,8,9]]
print(l) # [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print()

print(np.array(l))

# Output #
#  Matrix #
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Array Generation Function

In [65]:
kd=np.arange(1,11,3) # start end+1 jump		
print(kd) # [ 1  4  7 10]

a1=np.zeros(6) # float
a2=np.ones(6) # float
print(a1) # [0. 0. 0. 0. 0. 0.]
print(a2) # [1. 1. 1. 1. 1. 1.]

a3=np.zeros((3,5)) # float
print(a3)
# [[0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0.]]

a4=np.ones((3,5)) # float
print(a4)
# [[1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1.]]

[ 1  4  7 10]
[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
float64
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [66]:
b1=np.linspace(1,5,3) # two elements from 1 to 5 having same difference between consecutive two elements
print(b1) # [1. 3. 5.] -->float

[1. 3. 5.]


## Random Generation Function

#### Normalization and Standardization

In [85]:
b2=np.random.rand(5) # random-->library,rand-->library function
print(b2) # [0.46606165 0.07058798 0.32876915 0.47001342 0.48899499]
# All will be between 0 to 1 -->NORMALIZATION

b3=np.random.randn(5) # random-->library,randn-->library function
print(b3) # [0.46606165 0.07058798 0.32876915 0.47001342 0.48899499]
# All will be between -3 to 3 --> Standardization

b4=np.random.randint(5) # random-->library,randint-->library function
print(b4) # 0 1 2 3 4 -->Can be anything
# Generates random integer(single integer) between 0<=int<5

b5=np.random.randint(5,7,2) # (start) (end+1) (number of inetgers in between,default=1)
print(b5) # [5 6]


[0.31197018 0.47519078 0.79021876 0.61461494 0.61025294]
[ 1.09851274 -0.25223585 -0.11161788 -1.31096269  0.40620186]
1
[5 6]


## Array Attributes
* In NumPy, array attributes are built-in properties of ndarray objects that provide crucial metadata about an array's structural makeup, data types, and memory layout without modifying its contents.
* arr.shape,arr.size   no need of brackets in attributes()
* A variable inside a class/instance. is attribute

In [69]:
b12=np.array([[1,2,3,34],[4,5,6,102],[7,8,9,10]])
print(b12)
# [[  1   2   3  34]
#  [  4   5   6 102]
#  [  7   8   9  10]]

print(b12.shape)  # (rows,cols)-->shape-->(3,4)
print(b12.size)  # number of elements-->size-->12
print(b12.dtype)  # data type of vector-->int64

[[  1   2   3  34]
 [  4   5   6 102]
 [  7   8   9  10]]
(3, 4)
12
int64


## Array Methods
* NumPy arrays (ndarray objects) offer a powerful set of built-in methods and functions to perform fast, vectorized operations without the need for standard Python loops
* Method-->A function inside a class.

In [ ]:
c12=np.array([[1,2,3],[34,12,13],[4,5,6]])

print(c12.min()) # 1
print(c12.max()) # 34
#  Returns the lowest and highest values in the array 

print(c12.argmax()) # index of maximum element
print(c12.argmin()) # index of minimum element

print(c12.sum())  #  Calculates the total sum of all elements. --> 80
print(c12.prod())  #  Multiplies all elements together to return their product. --> 3818880
print(c12.mean())  #  Computes the arithmetic mean (average). --> 8.88888888888889

print(c12.std())  #  Computes the standard deviation of the elements. --> 9.711899281516514
print(c12.var())  #  Calculates the variance of the elements. --> 94.32098765432099

# [ 6 59 15]--> row wise sum

1
34
3
0
80
3818880
8.88888888888889
9.711899281516514
94.32098765432099
[39 19 22]
[ 6 59 15]


#### Reshape and Resize

In [95]:
b23=np.arange(1,31)
print(b23) 
# [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]

a15=b23.reshape(5,6) # number of elements should be same
print(a15) 
# original remain same but assigned new array get reshaped accordingly
# must be assigned
# [[ 1  2  3  4  5  6]
#  [ 7  8  9 10 11 12]
#  [13 14 15 16 17 18]
#  [19 20 21 22 23 24]
#  [25 26 27 28 29 30]]


b34=np.arange(1,31)
print(b34) 
# [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]

a16=np.resize(b34,(5,7)) # numer of elements must be greater or eqal,extra space gets filled with '0'
print(a16) 
# [[ 1  2  3  4  5  6  7]
#  [ 8  9 10 11 12 13 14]
#  [15 16 17 18 19 20 21]
#  [22 23 24 25 26 27 28]
#  [29 30  1  2  3  4  5]]


# b34.resize(5,7) # numer of elements must be greater or eqal,extra space gets filled with '0'
# print(b34) 
# assign nahi karna he ye original array ko hi resize krta he
# [[ 1  2  3  4  5  6  7]
#  [ 8  9 10 11 12 13 14]
#  [15 16 17 18 19 20 21]
#  [22 23 24 25 26 27 28]
#  [29 30  1  2  3  4  5]]

b34.resize(5,7,refcheck=False) # numer of elements must be greater or eqal,extra space gets filled with '0'
print(b34) # numbers repeat nahi honge
# [[ 1  2  3  4  5  6  7]
#  [ 8  9 10 11 12 13 14]
#  [15 16 17 18 19 20 21]
#  [22 23 24 25 26 27 28]
#  [29 30  0  0  0  0  0]]



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30  1  2  3  4  5]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30  0  0  0  0  0]]


## Array Indexing And Slincing

In [96]:
nums=np.arange(1,21)
print(nums) # [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

print(nums[12]) # 13 --> o-indexed
print(nums[1:5]) #[start:end+1:jump] (default start-->0(including) )(default end-->last element(including) ) (default jump-->1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


### Numpy Indexing and Slicing Of Matrix

In [116]:
nums1=np.arange(1,31).reshape(6,5)
print(nums1) 
# [[ 1  2  3  4  5]
#  [ 6  7  8  9 10]
#  [11 12 13 14 15]
#  [16 17 18 19 20]
#  [21 22 23 24 25]
#  [26 27 28 29 30]]

print(nums1[4]) # [21 22 23 24 25] -->4th row
print(nums1[:,3]) # [ 4  9 14 19 24 29]-->3rd col

print(nums1[3,4]) # 3rd row 4th col -->20 --> ALWAYS USE THIS
print(nums1[3][4]) # 3rd row 4th col -->20 -->DONT USE
# print(nums1[][4]) # [21 22 23 24 25] -->4th col

print(nums1[0:2,1:3]) # slicing properties same baki ki
# [[2 3]
#  [7 8]]
# print(nums1[0:2][1:3]) --> WRONG

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[21 22 23 24 25]
[ 4  9 14 19 24 29]
20
20
[[2 3]
 [7 8]]


### Boolean Indexing

In [124]:
nums2=np. arange(11,21)
print(nums2) # [11 12 13 14 15 16 17 18 19 20]

bool_idx=(nums2%2==0)
print(bool_idx) # [False  True False  True False  True False  True False  True]

nums2=nums2[bool_idx] #isko dubara nhi execute kar skte kyunki iske baad nums2 me jitne true the utne  honge pr bool_idx me 10 numbers can change
print(nums2) # [12 14 16 18 20]. array me jo index true the woh hi ayenge

[11 12 13 14 15 16 17 18 19 20]
[False  True False  True False  True False  True False  True]
[12 14 16 18 20]


# ARRAY OPERATIONS

### Arithmetic Operations

In [ ]:
# size of two arrays must be same for arithmetic ops

j1=np.array([1,2,3,4,5])
j2=np.array([1,2,3,4,5])

j3=j1+j2 # [2  4  6  8 10]
j4=j1-j2 # [0 0 0 0 0]
j5=j1*j2 # [1  4  9 16 25]
j6=j1/j2 # [1. 1. 1. 1. 1.]
j7=j1//j2 # [1 1 1 1 1]
j8=j1**j2 # [1    4   27  256 3125]

# No change in j1 and j2

print(j3)
print(j4)
print(j5)
print(j6)
print(j7)
print(j8)

[ 2  4  6  8 10]
[0 0 0 0 0]
[ 1  4  9 16 25]
[1. 1. 1. 1. 1.]
[1 1 1 1 1]
[   1    4   27  256 3125]


#### Broadcasting

In [130]:
j1+=100
print(j1) # [101 102 103 104 105] adds 100 to every element

[201 202 203 204 205]


#### Deep and Shallow Copy

In [131]:
# Slicing return you a deep copy(new meomery) {b=a.copy()}
# but simply making {b=a} and changing  b will make shallow copy (same meomery,cahanges applied to both)

#### Matrix Operations

In [138]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

#--------------#
# Multiplication #
#--------------#

print(A@B) # mathematical mulitplication summation of row col
# [[19 22]
#  [43 50]]

print(np.dot(A,B)) # mathematical mulitplication summation of row col
# [[19 22]
#  [43 50]]

print(A*B) # Normal index to index multiplication
# [[ 5 12]
#  [21 32]]


#------------#
# Transpose #
#------------#

A=A.T # A.=T -->wrong
print(A)
# [[1 3]
#  [2 4]]



[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]
[[1 3]
 [2 4]]


## Stacking Array-->Matrix cant be stacks only 1-D arrays

In [140]:
C=np.array([1,2,3,4,5])
D=np.array([1,2,3,4,5])

e=np.vstack((C,D))
# [[1 2 3 4 5]
#  [1 2 3 4 5]]

f=np.hstack((C,D)) 
# [1 2 3 4 5 1 2 3 4 5]

g=np.column_stack((C,D))
# [[1 1]
#  [2 2]
#  [3 3]
#  [4 4]
#  [5 5]]

print(e)
print(f)
print(g)

[[1 2 3 4 5]
 [1 2 3 4 5]]
[1 2 3 4 5 1 2 3 4 5]
[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]]


#### Splitting Array

In [ ]:
matrix = np.array([
    [10, 11, 12, 13, 14, 15],
    [20, 21, 22, 23, 24, 25],
    [30, 31, 32, 33, 34, 35],
    [40, 41, 42, 43, 44, 45]
])



# ==========================================
# 1. np.vsplit (Vertical Split - Row wise) --> equal hona chahiye division
# ==========================================
# Kaam: Rows ke beech me horizontal cut lagata hai.
# 4 rows ko 2 equal parts me todenge (2 rows each).

e = np.vsplit(matrix, 2)
print("Part 1:\n", e[0]) # Pehli 2 rows (10s aur 20s)
print("Part 2:\n", e[1]) # Baaki 2 rows (30s aur 40s)


# ==========================================
# 2. np.hsplit (Horizontal Split - Column wise) --> equal hona chahiye division
# ==========================================
# Kaam: Columns ke beech me vertical cut lagata hai.
# 6 columns ko 3 equal parts me todenge (2 columns each).

f = np.hsplit(matrix, 3)
print("Part 1:\n", f[0]) # Pehle 2 columns
print("Part 2:\n", f[1]) # Beech ke 2 columns
print("Part 3:\n", f[2]) # Aakhri 2 columns


# ==========================================
# 3. np.array_split (Uneven/Odd Splitting)
# ==========================================
# Kaam: Jab barabar divide nahi ho sakta tab ye crash nahi hota.
# 6 columns ko 4 parts me todenge. Pehle do parts bade honge.

g = np.array_split(matrix, 4, axis=1) 
print("Part 1 (Columns: 2):\n", g[0])
print("Part 2 (Columns: 2):\n", g[1])
print("Part 3 (Columns: 1):\n", g[2])
print("Part 4 (Columns: 1):\n", g[3])


# ==========================================
# 4. Custom Index Split (Specific jagah se cut)
# ==========================================
# Kaam: [1, 3] ka matlab hai: "Index 1 se pehle" aur "Index 3 se pehle" cut lagao.

h = np.split(matrix, [1, 3], axis=0) 
print("Part 1 (Row 0):\n", h[0])      
print("Part 2 (Row 1 to 2):\n", h[1]) 
print("Part 3 (Row 3 ke baad):\n", h[2]) 


print(matrix) # matrix ko change nahi karta
# [[10 11 12 13 14 15]
#  [20 21 22 23 24 25]
#  [30 31 32 33 34 35]
#  [40 41 42 43 44 45]]


Part 1:
 [[10 11 12 13 14 15]
 [20 21 22 23 24 25]]
Part 2:
 [[30 31 32 33 34 35]
 [40 41 42 43 44 45]]
Part 1:
 [[10 11]
 [20 21]
 [30 31]
 [40 41]]
Part 2:
 [[12 13]
 [22 23]
 [32 33]
 [42 43]]
Part 3:
 [[14 15]
 [24 25]
 [34 35]
 [44 45]]
Part 1 (Columns: 2):
 [[10 11]
 [20 21]
 [30 31]
 [40 41]]
Part 2 (Columns: 2):
 [[12 13]
 [22 23]
 [32 33]
 [42 43]]
Part 3 (Columns: 1):
 [[14]
 [24]
 [34]
 [44]]
Part 4 (Columns: 1):
 [[15]
 [25]
 [35]
 [45]]
Part 1 (Row 0):
 [[10 11 12 13 14 15]]
Part 2 (Row 1 to 2):
 [[20 21 22 23 24 25]
 [30 31 32 33 34 35]]
Part 3 (Row 3 ke baad):
 [[40 41 42 43 44 45]]
[[10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]]
