# Valid Sudoku

In [3]:
import numpy as np

In [4]:
s=np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [20]:
a = np.sum(s, axis=1)  # rows
b = np.sum(s, axis=0)  # cols

a = a[a == 45]
b = b[b == 45]

if b.size != a.size or a.size != 9:
    print("Not valid")
else:
    valid=True

    for i in range(0, 9, 3):
        for j in range(0, 9, 3):
            c=s[i:i+3, j:j+3]
            if(c.sum() != 45):
                valid=False
                break
        if not valid:
            break

    if valid:
        print("Valid")
    else:
        print("Not valid")

Valid


In [99]:
# Columns: [Age, Math Marks, Science Marks]

data = np.array([
    [18, 85, 78],  # Student 1
    [19, 92, 88],  # Student 2
    [17, 76, 95],  # Student 3
    [18, 65, 70],  # Student 4
    [20, 90, 85]   # Student 5
])

In [36]:
print(data.shape)

(5, 3)


In [37]:
print(data.mean())

61.06666666666667


In [38]:
print(data[:,1])

[85 92 76 65 90]


In [39]:
a=data[:,2]
print(a.max())

95


In [41]:
print(data[data[:,1]>90])

[[19 92 88]]


In [46]:
print(data[:1]+5)

[[23 90 83]]


In [65]:
a=data[:,0]<19
a=a[a]
print(len(a))

3


In [71]:
x=data[:,1:]
print(x.mean(axis=0))

[81.6 83.2]


In [89]:
y=data[:,1]>=80
z=data[:,2]>=80
print(y)
print(z)
ab=ab[((y & z)==True)]
print(len(ab))

[ True  True False False  True]
[False  True  True False  True]
2


In [100]:
data[:,2][data[:,2]<75]=0
print(data)

[[18 85 78]
 [19 92 88]
 [17 76 95]
 [18 65  0]
 [20 90 85]]
